# Generated by Django 3.2.7 on 2021-09-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id']},
        ),
    ]
