# Generated by Django 3.2.7 on 2021-10-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcode', '0004_auto_20210916_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweetcode.posts'),
        ),
    ]
