# Generated by Django 3.2.7 on 2021-10-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcode', '0005_posts_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='parent',
        ),
    ]
