# Generated by Django 3.2.7 on 2021-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcode', '0007_auto_20211006_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
